export default {
  name: 'Mario Party',
  description: 'A funny festival with lots of games',
  fixtureAreas: [
    {
      id: 36,
      name: 'Stage',
      locationStart: '(200,20)',
      locationEnd: '(1800,300)',
    },
  ],
  seatAreas: [
    {
      id: 1,
      name: 'Main Seat Area',
      capacity: 100,
      reserved: 0,
      occupied: 0,
      locationStart: '(200,500)',
      locationEnd: '(1800,925)',
    },
  ],
  numberedSeats: [
    {
      id: 2,
      name: 'A1',
      location: '(200,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 3,
      name: 'A2',
      location: '(300,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 4,
      name: 'A3',
      location: '(400,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 5,
      name: 'A4',
      location: '(500,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 6,
      name: 'A5',
      location: '(600,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 7,
      name: 'A6',
      location: '(700,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 8,
      name: 'A7',
      location: '(800,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 9,
      name: 'A8',
      location: '(900,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 10,
      name: 'A9',
      location: '(1000,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 11,
      name: 'A10',
      location: '(1100,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 12,
      name: 'A11',
      location: '(1200,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 13,
      name: 'A12',
      location: '(1300,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 14,
      name: 'A13',
      location: '(1400,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 15,
      name: 'A14',
      location: '(1500,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 16,
      name: 'A15',
      location: '(1500,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 17,
      name: 'A15',
      location: '(1700,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 18,
      name: 'A17',
      location: '(1800,350)',
      reserved: false,
      occupied: false,
    },
    {
      id: 19,
      name: 'B1',
      location: '(200,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 20,
      name: 'B2',
      location: '(300,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 21,
      name: 'B3',
      location: '(400,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 22,
      name: 'B4',
      location: '(500,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 23,
      name: 'B5',
      location: '(600,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 24,
      name: 'B6',
      location: '(700,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 25,
      name: 'B7',
      location: '(800,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 26,
      name: 'B8',
      location: '(900,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 27,
      name: 'B9',
      location: '(1000,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 28,
      name: 'B10',
      location: '(1100,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 29,
      name: 'B11',
      location: '(1200,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 30,
      name: 'B12',
      location: '(1300,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 31,
      name: 'B13',
      location: '(1400,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 32,
      name: 'B14',
      location: '(1500,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 33,
      name: 'B15',
      location: '(1500,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 34,
      name: 'B15',
      location: '(1700,450)',
      reserved: false,
      occupied: false,
    },
    {
      id: 35,
      name: 'B17',
      location: '(1800,450)',
      reserved: false,
      occupied: false,
    },
  ],
  genericAreas: [],
  pricings: [
    { seat: 22, pricing: [4, 3] },
    { seat: 11, pricing: [4, 3] },
    { seat: 9, pricing: [4, 3] },
    { seat: 15, pricing: [4, 3] },
    { seat: 26, pricing: [4, 3] },
    { seat: 19, pricing: [4, 3] },
    { seat: 30, pricing: [4, 3] },
    { seat: 21, pricing: [4, 3] },
    { seat: 3, pricing: [4, 3] },
    { seat: 17, pricing: [4, 3] },
    { seat: 28, pricing: [4, 3] },
    { seat: 5, pricing: [4, 3] },
    { seat: 29, pricing: [4, 3] },
    { seat: 4, pricing: [4, 3] },
    { seat: 34, pricing: [4, 3] },
    { seat: 10, pricing: [4, 3] },
    { seat: 35, pricing: [4, 3] },
    { seat: 6, pricing: [4, 3] },
    { seat: 31, pricing: [4, 3] },
    { seat: 14, pricing: [4, 3] },
    { seat: 13, pricing: [4, 3] },
    { seat: 2, pricing: [4, 3] },
    { seat: 16, pricing: [4, 3] },
    { seat: 32, pricing: [4, 3] },
    { seat: 7, pricing: [4, 3] },
    { seat: 12, pricing: [4, 3] },
    { seat: 24, pricing: [4, 3] },
    { seat: 25, pricing: [4, 3] },
    { seat: 20, pricing: [4, 3] },
    { seat: 33, pricing: [4, 3] },
    { seat: 1, pricing: [2, 1] },
    { seat: 18, pricing: [4, 3] },
    { seat: 27, pricing: [4, 3] },
    { seat: 23, pricing: [4, 3] },
    { seat: 8, pricing: [4, 3] },
  ],
}
